In [1]:
import numpy as np

In [4]:
valoraciones = np.array([
    [8,7,8,5], 
    [2,6,8,1], 
    [8,8,9,5]
])

valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [8]:
# 1ra forma de mostrar un valor
valoraciones[0][1]

7

In [9]:
# 2da forma de mostrar un valor
valoraciones[0,1]

7

In [31]:
valores2 = np.zeros((3,2,4))

In [32]:
valores2 + np.ones((3,2,4))

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [33]:
# calculando la media
np.mean(valores2)

1.0

In [35]:
np.mean(valores2, axis=2)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [43]:
np.median(df["Columna1"])

NameError: name 'df' is not defined

In [46]:
# crea arrays random
np.random.rand(2,2)

array([[0.94560522, 0.77876163],
       [0.09496614, 0.53643341]])